def ferdinandFlowers = [
    item("ferdinandsflowers:block_cff_flowers"),
    item("ferdinandsflowers:block_cff_flowers", 1),
    item("ferdinandsflowers:block_cff_flowers", 2),
    item("ferdinandsflowers:block_cff_flowers", 3),
    item("ferdinandsflowers:block_cff_flowers", 4),
    item("ferdinandsflowers:block_cff_flowers", 5),
    item("ferdinandsflowers:block_cff_flowers", 6),
    item("ferdinandsflowers:block_cff_flowers", 7),
    item("ferdinandsflowers:block_cff_flowers", 8),
    item("ferdinandsflowers:block_cff_flowers", 9),
    item("ferdinandsflowers:block_cff_flowers", 10),
    item("ferdinandsflowers:block_cff_flowers", 11),
    item("ferdinandsflowers:block_cff_flowers", 12),
    item("ferdinandsflowers:block_cff_flowers", 13),
    item("ferdinandsflowers:block_cff_flowers", 14),
    item("ferdinandsflowers:block_cff_flowers", 15),
    item("ferdinandsflowers:block_cff_flowersb"),
    item("ferdinandsflowers:block_cff_flowersb", 1),
    item("ferdinandsflowers:block_cff_flowersb", 2),
    item("ferdinandsflowers:block_cff_flowersb", 3),
    item("ferdinandsflowers:block_cff_flowersb", 4),
    item("ferdinandsflowers:block_cff_flowersb", 5),
    item("ferdinandsflowers:block_cff_flowersb", 6),
    item("ferdinandsflowers:block_cff_flowersb", 7),
    item("ferdinandsflowers:block_cff_flowersb", 8),
    item("ferdinandsflowers:block_cff_flowersb", 9),
    item("ferdinandsflowers:block_cff_flowersb", 10),
    item("ferdinandsflowers:block_cff_flowersb", 11),
    item("ferdinandsflowers:block_cff_flowersb", 12),
    item("ferdinandsflowers:block_cff_flowersb", 13),
    item("ferdinandsflowers:block_cff_flowersb", 14),
    item("ferdinandsflowers:block_cff_flowersb", 15),
    item("ferdinandsflowers:block_cff_flowersc"),
    item("ferdinandsflowers:block_cff_flowersc", 1),
    item("ferdinandsflowers:block_cff_flowersc", 2),
    item("ferdinandsflowers:block_cff_flowersc", 3),
    item("ferdinandsflowers:block_cff_flowersc", 4),
    item("ferdinandsflowers:block_cff_flowersc", 5),
    item("ferdinandsflowers:block_cff_flowersc", 6),
    item("ferdinandsflowers:block_cff_flowersc", 7),
    item("ferdinandsflowers:block_cff_flowersc", 8),
    item("ferdinandsflowers:block_cff_flowersc", 9),
    item("ferdinandsflowers:block_cff_flowersc", 10),
    item("ferdinandsflowers:block_cff_flowersc", 11),
    item("ferdinandsflowers:block_cff_flowersc", 12),
    item("ferdinandsflowers:block_cff_flowersc", 13),
    item("ferdinandsflowers:block_cff_flowersc", 14),
    item("ferdinandsflowers:block_cff_flowersc", 15),
    item("ferdinandsflowers:block_cff_flowersd"),
    item("ferdinandsflowers:block_cff_flowersd", 1),
    item("ferdinandsflowers:block_cff_flowersd", 2),
    item("ferdinandsflowers:block_cff_flowersd", 3),
    item("ferdinandsflowers:block_cff_flowersd", 4),
    item("ferdinandsflowers:block_cff_flowersd", 5),
    item("ferdinandsflowers:block_cff_flowersd", 6),
    item("ferdinandsflowers:block_cff_flowersd", 7),
    item("ferdinandsflowers:block_cff_flowersd", 8),
    item("ferdinandsflowers:block_cff_flowersd", 9),
    item("ferdinandsflowers:block_cff_flowersd", 10),
    item("ferdinandsflowers:block_cff_flowersd", 11),
    item("ferdinandsflowers:block_cff_flowersd", 12),
    item("ferdinandsflowers:block_cff_flowersd", 13),
    item("ferdinandsflowers:block_cff_flowersd", 14),
    item("ferdinandsflowers:block_cff_flowersd", 15),
    item("ferdinandsflowers:block_cff_flowerse"),
    item("ferdinandsflowers:block_cff_flowerse", 1),
    item("ferdinandsflowers:block_cff_flowerse", 2),
    item("ferdinandsflowers:block_cff_flowerse", 3),
    item("ferdinandsflowers:block_cff_flowerse", 4),
    item("ferdinandsflowers:block_cff_flowerse", 5),
    item("ferdinandsflowers:block_cff_flowerse", 6),
    item("ferdinandsflowers:block_cff_flowerse", 7),
    item("ferdinandsflowers:block_cff_flowerse", 8),
    item("ferdinandsflowers:block_cff_flowerse", 9),
    item("ferdinandsflowers:block_cff_flowerse", 10),
    item("ferdinandsflowers:block_cff_flowerse", 11),
    item("ferdinandsflowers:block_cff_flowerse", 12),
    item("ferdinandsflowers:block_cff_flowerse", 13),
    item("ferdinandsflowers:block_cff_flowerse", 14),
    item("ferdinandsflowers:block_cff_flowerse", 15),
    item("ferdinandsflowers:block_cff_doubles"),
    item("ferdinandsflowers:block_cff_doubles", 1),
    item("ferdinandsflowers:block_cff_doubles", 2),
    item("ferdinandsflowers:block_cff_doubles", 3),
    item("ferdinandsflowers:block_cff_doubles", 4),
    item("ferdinandsflowers:block_cff_doubles", 5),
    item("ferdinandsflowers:block_cff_doublesb"),
    item("ferdinandsflowers:block_cff_doublesb", 1),
    item("ferdinandsflowers:block_cff_doublesb", 2),
    item("ferdinandsflowers:block_cff_doublesb", 3),
    item("ferdinandsflowers:block_cff_doublesb", 4),
    item("ferdinandsflowers:block_cff_doublesb", 5),
    item("ferdinandsflowers:block_cff_doublesc"),
    item("ferdinandsflowers:block_cff_doublesc", 1),
    item("ferdinandsflowers:block_cff_doublesc", 2),
    item("ferdinandsflowers:block_cff_doublesc", 3),
    item("ferdinandsflowers:block_cff_doublesc", 4),
    item("ferdinandsflowers:block_cff_doublesc", 5),
    item("ferdinandsflowers:block_cff_doubless"),
    item("ferdinandsflowers:block_cff_doubless", 1),
    item("ferdinandsflowers:block_cff_doubless", 2),
    item("ferdinandsflowers:block_cff_doubless", 3),
    item("ferdinandsflowers:block_cff_doubless", 4),
    item("ferdinandsflowers:block_cff_doubless", 5),
    item("ferdinandsflowers:block_cff_doublesp"),
    item("ferdinandsflowers:block_cff_doublesp", 1),
    item("ferdinandsflowers:block_cff_doublesp", 2),
    item("ferdinandsflowers:block_cff_doublesp", 3),
    item("ferdinandsflowers:block_cff_doublesp", 4),
    item("ferdinandsflowers:block_cff_doublesp", 5),
    item("ferdinandsflowers:block_cff_desert"),
    item("ferdinandsflowers:block_cff_desert", 1),
    item("ferdinandsflowers:block_cff_desert", 2),
    item("ferdinandsflowers:block_cff_desert", 3),
    item("ferdinandsflowers:block_cff_desert", 4),
    item("ferdinandsflowers:block_cff_desert", 5),
    item("ferdinandsflowers:block_cff_desert", 6),
    item("ferdinandsflowers:block_cff_desert", 7),
    item("ferdinandsflowers:block_cff_desert", 8),
    item("ferdinandsflowers:block_cff_desert", 9),
    item("ferdinandsflowers:block_cff_desert", 10),
    item("ferdinandsflowers:block_cff_desert", 11),
    item("ferdinandsflowers:block_cff_desert", 12),
    item("ferdinandsflowers:block_cff_desert", 13),
    item("ferdinandsflowers:block_cff_desert", 14),
    item("ferdinandsflowers:block_cff_desert", 15),
    item("ferdinandsflowers:block_cff_ouch"),
    item("ferdinandsflowers:block_cff_ouch", 1),
    item("ferdinandsflowers:block_cff_ouch", 2),
    item("ferdinandsflowers:block_cff_ouch", 3),
    item("ferdinandsflowers:block_cff_ouch", 4),
    item("ferdinandsflowers:block_cff_doublesd"),
    item("ferdinandsflowers:block_cff_doublesd", 1),
    item("ferdinandsflowers:block_cff_doublesd", 2),
    item("ferdinandsflowers:block_cff_doublesd", 3),
    item("ferdinandsflowers:block_cff_doublesd", 4),
    item("ferdinandsflowers:block_cff_doublesd", 5),
    item("ferdinandsflowers:block_cff_fungus"),
    item("ferdinandsflowers:block_cff_fungus", 1),
    item("ferdinandsflowers:block_cff_fungus", 2),
    item("ferdinandsflowers:block_cff_fungus", 3),
    item("ferdinandsflowers:block_cff_dark"),
    item("ferdinandsflowers:block_cff_dark", 1)
]

for (flower in ferdinandFlowers) {
    ore_dict.add('flower', flower)
    ore_dict.add('allFlowers', flower)
}
