mods.roots.transmutation.recipeBuilder()
    .name('amber_transmutation')
    .start(blockstate('biomesoplenty:gem_ore', 'variant=amber'))
    .output(item('fossil:amber_ore'))
.register()

mods.roots.transmutation.recipeBuilder()
    .name('amber_transmutation_thaumcraft')
    .start(blockstate('thaumcraft:ore_amber'))
    .output(item('fossil:amber_ore'))
.register()

mods.roots.transmutation.recipeBuilder()
    .name('copper_aluminum_transmutation')
    .start(blockstate('thermalfoundation:storage', 'type=copper'))
    .output(item('thermalfoundation:storage', 4))
.register()
