#Button Bindings
#Thu Dec 25 15:39:17 GMT-03:00 2025
controllable.key.moveDown=controllable.button.dpad_down
controllable.key.moveLeft=controllable.button.dpad_left
controllable.key.moveRight=controllable.button.dpad_right
controllable.key.moveUp=controllable.button.dpad_up
controllable.key.nextCreativeTab=controllable.button.right_bumper
controllable.key.nextHotbarItem=controllable.button.right_bumper
controllable.key.nextRecipeTab=controllable.button.right_trigger
controllable.key.pauseGame=controllable.button.start
controllable.key.previousCreativeTab=controllable.button.left_bumper
controllable.key.previousHotbarItem=controllable.button.left_bumper
controllable.key.previousRecipeTab=controllable.button.left_trigger
key.attack=controllable.button.right_trigger
key.drop=controllable.button.dpad_down
key.inventory=controllable.button.y
key.jump=controllable.button.a
key.pickItem=controllable.button.dpad_left
key.playerlist=controllable.button.select
key.sneak=controllable.button.right_thumb_stick
key.sprint=controllable.button.left_thumb_stick
key.swapOffhand=controllable.button.x
key.togglePerspective=controllable.button.dpad_up
key.use=controllable.button.left_trigger
